//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace TunnelBuilder.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("TunnelSupport", Namespace="http://tempuri.org/TunnelSupportSchema.xsd", IsNullable=false)]
    public partial class TunnelSupportType {
        
        private Bolt boltField;
        
        private Shotcrete shotcreteField;
        
        private System.DateTime orderDateField;
        
        private bool orderDateFieldSpecified;
        
        /// <remarks/>
        public Bolt Bolt {
            get {
                return this.boltField;
            }
            set {
                this.boltField = value;
            }
        }
        
        /// <remarks/>
        public Shotcrete Shotcrete {
            get {
                return this.shotcreteField;
            }
            set {
                this.shotcreteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderDateSpecified {
            get {
                return this.orderDateFieldSpecified;
            }
            set {
                this.orderDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class Bolt {
        
        private Alignment alignmentField;
        
        /// <remarks/>
        public Alignment Alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class Alignment {
        
        private SupportInterval intervalField;
        
        private string nameField;
        
        /// <remarks/>
        public SupportInterval Interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class SupportInterval {
        
        private double fromField;
        
        private double toField;
        
        private BoltSupportType supportTypeField;
        
        /// <remarks/>
        public double From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public double To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public BoltSupportType SupportType {
            get {
                return this.supportTypeField;
            }
            set {
                this.supportTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class BoltSupportType {
        
        private double lengthField;
        
        private bool lengthFieldSpecified;
        
        private double transversiveSpacingField;
        
        private bool transversiveSpacingFieldSpecified;
        
        private double longitudinalSpacingField;
        
        private bool longitudinalSpacingFieldSpecified;
        
        private bool staggeredField;
        
        private bool staggeredFieldSpecified;
        
        private bool crownOnlyField;
        
        private bool crownOnlyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double TransversiveSpacing {
            get {
                return this.transversiveSpacingField;
            }
            set {
                this.transversiveSpacingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransversiveSpacingSpecified {
            get {
                return this.transversiveSpacingFieldSpecified;
            }
            set {
                this.transversiveSpacingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double LongitudinalSpacing {
            get {
                return this.longitudinalSpacingField;
            }
            set {
                this.longitudinalSpacingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudinalSpacingSpecified {
            get {
                return this.longitudinalSpacingFieldSpecified;
            }
            set {
                this.longitudinalSpacingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Staggered {
            get {
                return this.staggeredField;
            }
            set {
                this.staggeredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StaggeredSpecified {
            get {
                return this.staggeredFieldSpecified;
            }
            set {
                this.staggeredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CrownOnly {
            get {
                return this.crownOnlyField;
            }
            set {
                this.crownOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrownOnlySpecified {
            get {
                return this.crownOnlyFieldSpecified;
            }
            set {
                this.crownOnlyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class Shotcrete {
    }
}
