//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace TunnelBuilder.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd", IsNullable=false)]
    public partial class TunnelSupportDefinition {
        
        private BoltSupportLength[] boltSupportLengthsField;
        
        private GroundCondition[] groundConditionsField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BoltSupportLength[] BoltSupportLengths {
            get {
                return this.boltSupportLengthsField;
            }
            set {
                this.boltSupportLengthsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GroundCondition[] GroundConditions {
            get {
                return this.groundConditionsField;
            }
            set {
                this.groundConditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class BoltSupportLength {
        
        private double tunnelSpanField;
        
        private bool tunnelSpanFieldSpecified;
        
        private double lengthField;
        
        private bool lengthFieldSpecified;
        
        private bool staggeredField;
        
        private bool staggeredFieldSpecified;
        
        private bool crownOnlyField;
        
        private bool crownOnlyFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double TunnelSpan {
            get {
                return this.tunnelSpanField;
            }
            set {
                this.tunnelSpanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TunnelSpanSpecified {
            get {
                return this.tunnelSpanFieldSpecified;
            }
            set {
                this.tunnelSpanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Staggered {
            get {
                return this.staggeredField;
            }
            set {
                this.staggeredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StaggeredSpecified {
            get {
                return this.staggeredFieldSpecified;
            }
            set {
                this.staggeredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CrownOnly {
            get {
                return this.crownOnlyField;
            }
            set {
                this.crownOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrownOnlySpecified {
            get {
                return this.crownOnlyFieldSpecified;
            }
            set {
                this.crownOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TunnelSupportSchema.xsd")]
    public partial class GroundCondition {
        
        private double transversiveSpacingField;
        
        private bool transversiveSpacingFieldSpecified;
        
        private double longitudinalSpacingField;
        
        private bool longitudinalSpacingFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double TransversiveSpacing {
            get {
                return this.transversiveSpacingField;
            }
            set {
                this.transversiveSpacingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransversiveSpacingSpecified {
            get {
                return this.transversiveSpacingFieldSpecified;
            }
            set {
                this.transversiveSpacingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double LongitudinalSpacing {
            get {
                return this.longitudinalSpacingField;
            }
            set {
                this.longitudinalSpacingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudinalSpacingSpecified {
            get {
                return this.longitudinalSpacingFieldSpecified;
            }
            set {
                this.longitudinalSpacingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
